_core:
  default_config_hash: AOXdYmkvKEWQ90i8bbStpi07jONjN29ny1BcgITQFSM
langcode: en
site_settings:
  default_icon: home-smoke
  theme_color: coat-of-arms
  koro: basic
footer_settings:
  footer_color: dark
  footer_top_title: 'Contact information'
  footer_top_content:
    value: '<p><a href="#">Search for contacts and phone numbers</a></p><p><a href="#" class="hds-button hds-button--secondary"><span aria-hidden="true" class="hel-icon hel-icon--phone"></span><span class="hds-button__label">Helsinki-info 09 310 1691</span></a></p>'
    format: full_html
